command = "i3status-rs"

background = "#1f1f28"
color = "#dcd7ba"
tag_fg = "#e0def4"
tag_bg = "#1f1f28"
tag_focused_fg = "#16161d"
tag_focused_bg = "#957fb8"
tag_urgent_fg = "#16161d"
tag_urgent_bg = "#e82424"
tag_inactive_fg = "#6e6a86"
tag_inactive_bg = "#1f1d2e"

font = "Mononoki Nerd Font 20"
height = 30 
separator_width = 0
tags_r = 0
tags_padding = 15
blocks_r = 0
blocks_overlap = 0

position = "top"
hide_inactive_tags = false
show_layout_name = false
# blend = true
# show_mode = true

[wm.river]
max_tag = 5
