icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#dca561"
idle_fg = "#16161d"
good_bg = "#76946a"
good_fg = "#16161d"
warning_bg = "#ff9e3b"
warning_fg = "#16161d"
critical_bg = "#e82424"
critical_fg = "#16161d"
info_bg = "#dcd7ba"
info_fg = "#191724"
separator = "native"
alternating_tint_bg = "none"
alternating_tint_fg = "none"

[icons]
icons = "material-nf"

[[block]]
block = "battery"

[[block]]
block = "sound"
show_volume_when_muted = true
max_vol = 100
[block.theme_overrides]
idle_bg = "#7e9cd8"
[block.icons_overrides]
volume_muted = ""
volume = ""
[[block.click]]
button = "left"
cmd = "pamixer -t"

[[block]]
block = "backlight"
[block.theme_overrides]
idle_bg = "#98bb6c"
[block.icons_overrides]
backlight = "󰃞"

[[block]]
block = "bluetooth"
mac = "7C:9A:1D:A1:DD:2E"
disconnected_format = ""
format = " $icon $name "

[[block]]
block = "custom"
cycle = ["blt", "blt"]
interval = "once"
[[block.click]]
button = "left"
action = "cycle"

[[block]]
block = "net"
format = " $icon $ssid "
[[block.click]]
button = "left"
cmd = "nm-connection-editor"


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%R') "
[block.theme_overrides]
idle_bg = "#e46876"

