config.bind("cs", "config-source")
config.bind("sm", "hint links spawn mpv {hint-url}")
config.bind("sM", "spawn mpv {url}")
config.bind("eu", "edit-url")
config.bind("ef", "config-cycle statusbar.show never always;; config-cycle tabs.show never always")
