'$schema' = 'https://starship.rs/config-schema.json'

format = '$character$directory$git_branch$git_status'

right_format = '$battery$time'

[battery]
format = '[$percentage]($style) '
disabled = false

[[battery.display]]
threshold = 101
style = 'cyan'

[time]
time_format = '%H:%M'
format = 'at [$time]($style)'
style = 'bold purple'
disabled = false

[directory]
style = 'white'
truncation_length = 1
read_only = ' [RO]'

[character]
success_symbol = '[λ](yellow)'
error_symbol = '[λ](bold red)'
vimcmd_symbol = '[∆](yellow)'

[git_branch]
format = "[\\(](blue)[$branch]($style)[\\)](blue)"
style = 'red'

[git_status]
format = '[($conflicted$untracked$modified$staged$renamed$deleted)]($style) '
style = 'red'
conflicted = '​'
untracked = '​'
modified = '​'
staged = '​'
renamed = '​'
deleted = '​'
